### ISSUE TITLE
Race series, basic structure.

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/flammerougeracing#2]
A race series will track the total points from 1 or more races across categories and have a race series result/points view calculated from the individual races.
- app admin can make/edit/delete... race series
- user can see and enter race series.

**proposed fields:**
- name
- start and end date
- Description
- logo, smaller image ~256X256 ? depends on page layout

**Model link to other tables:**
- link to table: event scoring matrix. More on this in another issue
- link to table:  many race results. More on this in another issue
- link to table: Many users entered in race series. More on this in another issue

**Comment by karthicksakkaravarti** [comment]
can u please create issues for below items,
link to table: event scoring matrix. More on this in another issue
link to table: many race results. More on this in another issue
link to table: Many users entered in race series. More on this in another issue
