### ISSUE TITLE
Basic user account

### ISSUE THREAD

**Issue by vincentdavis** [we-race-here/flammerougeracing#5]
Basic user account:
- Require verified email or passkey, see issue #3 
**Fields**
- email, required
- First name (required)
- Last name (required)
- zwiftID, not required at signup, is required for race. See issue #1 
- Zwift Race category (A, B, C, D, E) (required)
- Gender (required)
- discord id or profile. Can we link to this and send messages See issue number #4

**Comment by karthicksakkaravarti** [comment]
http://165.232.188.93:8008/accounts/login/?next=/#/signup
